{ den, ... }:
let
  hostname = "snow-rainbow";
  stateVersion = "26.05";
in
{
  den.hosts.x86_64-linux.${hostname} = {
    # this should be kept as the nixos release version of the first install of this system!
    systSettings = { inherit stateVersion; };

    # declare users on this host
    # (generally, customize them in their autogenerated user aspect `den.aspects.users.<username>`)
    users = {
      meow = {
        # enable integrated home manager
        # (specifically, it allows a `homeManager= {};` class module in the user's aspect, which is
        # forwarded to `home-manager.users.<username>` as with usual integrated home manager configs)
        classes = [ "homeManager" ];
      };
    };
  };

  # enable standalone home manager for users on this host
  # (standalone and integrated home manager entities both pull from `den.aspects.user.<username>`)
  # (snow-rainbow is a fully fledged nixos host so this is mainly for testing standalones)
  den.homes.x86_64-linux = {
    # by specifying both username and hostname, we tie this automatically to the user aspect,
    # and also allows you to invoke standalone home manager with just `home-manager switch`
    "meow@${hostname}" = {
      systSettings = { inherit stateVersion; };
    };
  };

  den.aspects.hosts.${hostname} = {
    # aspects to be included on this host regardless of user
    includes = [
      den.aspects.hosts.base

      den.aspects.features.system.dual-boot
      den.aspects.features.system.firmware
      den.aspects.features.system.nixowos

      # (note that greeter can manage different WMs/DEs per user)
      den.aspects.features.desktop.noctalia-greeter

      den.aspects.features.tools.nvtop     # `top` for GPUs
      den.aspects.features.tools.playerctl # control media players that use MPRIS
      den.aspects.features.tools.solaar    # logitech mouse config
      den.aspects.features.tools.tokei

      den.aspects.features.apps.firefox
    ];
  };
}
