" uncomment the next line to make Vim more vi-compatible
" NOTE: `debian.vim` sets `nocompatible`. setting `compatible` changes numerous options, so any other options
" should be set AFTER setting `compatible`
"set compatible

" vim5 and later versions support syntax highlighting
" uncommenting the next line enables syntax highlighting by default
if has('syntax')
    syntax on
endif

" if using a dark background within the editing area and syntax highlighting, turn on this option as well
"set background=dark

" uncomment the following to have vim jump to the last position when reopening a file
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" uncomment the following to have vim load indentation rules and plugins according to the detected filetype
filetype plugin indent on

" the following are commented out as they cause vim to behave a lot differently from regular vi
" they are highly recommended though
set showcmd                                     " show (partial) command in status line
set showmatch                                   " show matching brackets
"set ignorecase                                 " do case insensitive matching
set smartcase                                   " do smart case matching
set incsearch                                   " incremental search
set autowrite                                   " automatically save before commands like `:next` and `:make`
set hidden                                      " hide buffers when they are abandoned
set mouse=a                                     " enable mouse usage (all modes)

" source a global configuration file if available
"if filereadable('/etc/vim/vimrc.local')
"    source /etc/vim/vimrc.local
"endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugin Configs
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" CamelCaseMotion
let g:camelcasemotion_key='<leader>'

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Custom Configs
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set colorcolumn=121                                 " vertical rule to guide line widths
set hlsearch                                        " searching permanently highlights all matches
set iskeyword-=_                                    " things like `w` in normal mode always stop at underscores too
autocmd FileType fish setlocal iskeyword-=_
autocmd FileType fish setlocal iskeyword-=.
autocmd FileType css,fish,nix setlocal iskeyword-=- " things like `w` in normal mode always stop at hyphens too
set laststatus=2                                    " always shows status line at bottom
set nu rnu                                          " hybrid line numbers
set scrolloff=2                                     " scrolling always keeps 2 lines visible around cursor
set viminfo='256,<65535                             " yank up to 65535 lines and remember marks from 256 files

set shiftwidth=4                                    " `tab` is 4 spaces wide
set smarttab expandtab                              " pressing `tab` gives `shiftwidth` spaces
set tabstop=8                                       " actual tab chars are 8 spaces wide to avoid confusion with indents

set termguicolors                                   " for custom colorscheme
set cursorline
autocmd BufEnter * :colorscheme anonymousrand       " always apply custom colorscheme last when entering buffer

set visualbell                                      " turn off bell sounds in vim, for WSL mainly
set t_vb=

let mapleader=','

" breaks undo every time `space`, `enter`, or `ctrl + w` is pressed, allowing individual words to be undone
inoremap <Space> <Space><C-g>u
inoremap <CR> <CR><C-g>u
inoremap <C-w> <C-g>u<C-w>
nnoremap <p> <C-g>up

" search results are brought to middle of screen
nnoremap n nzz
nnoremap N Nzz

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Custom Keybinds
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" `ctrl + c` to copy to system clipboard (XA_CLIPBOARD) in visual mode, and `ctrl + v` to paste from XA_CLIPBOARD
" (may already be set by terminal, but just in case)
vnoremap <C-c> "+y
nnoremap <C-v> "+p

" `ctrl + p` to paste from `0` register (where the last yank lives, unaffected by deletes) in normal and visual modes
nnoremap <C-p> "0p
vnoremap <C-p> "0p

" `ctrl + s` to save in normal and insert modes
nnoremap <C-s> :w<CR>
inoremap <C-s> <ESC>:w<CR>a

" `ctrl + backspace` to delete whole word in insert mode (`ctrl + h` is sent instead on Linux terminals)
inoremap <C-BS> <C-w>
inoremap <C-h> <C-w>

" `enter` to insert new line below in normal mode (`shift + enter` doesn't work though)
nnoremap <Enter> o<ESC>
