{
  den.hosts.x86_64-linux.desktop = {
    hostName = "snow-rainbow";
    # this should be kept as the nixos release version of the first install of this system!
    stateVersion = "26.05";

    # declare users on this host
    # (generally, customize them in their autogenerated user aspect `den.aspects.users.<username>`)
    users = {
      meow = {
        # enable integrated home manager
        # (specifically, it allows a `homeManager= {};` class module in the user's aspect, which is
        # fed to `home-manager.users.<username>` as with usual integrated home manager configs)
        classes = [ "homeManager" ];
      };
    };
  };

  # enable standalone home manager for users on this host
  # (standalone and integrated home manager entities both pull from `den.aspects.user.<username>`)
  den.homes.x86_64-linux = {
    "meow@desktop" = {};
  };

  den.aspects.hosts.desktop = {
    # aspects to be included on this host regardless of user
    # (as of den v0.3.0, any `homeManager` class modules in these includes are automatically
    # forwarded to all users on this host, while `nixos` class modules are evaluated immediately
    # within the context of this host as usual)
    includes = [
      den.aspects.features.system.dual-boot
      den.aspects.features.system.firmware
      den.aspects.features.system.nixowos
      den.aspects.features.system.nvidia

      # (note that greeter can manage different WMs/DEs per user)
      den.aspects.features.desktop.noctalia-greeter

      den.aspects.features.tools.bottom
      den.aspects.features.tools.nvtop     # `top` for GPUs
      den.aspects.features.tools.playerctl # control media players that use MPRIS
      den.aspects.features.tools.solaar    # logitech mouse config
      den.aspects.features.tools.tokei

      den.aspects.features.apps.firefox
    ];
  };
}
