{
  den.hosts.x86_64-linux.desktop = {
    hostName = "snow-rainbow";
    # this should be kept as the nixos release version of the first install of this system!
    stateVersion = "26.05";

    # declare users on this host
    # host-specific customization for users goes here, host-agnostic customization
    # goes in their autogenerated user aspect (`den.aspects.<username>`)
    users = {
      meow = {
        # enable integrated home manager
        # specifically, it allows a `homeManager= {};` class module in the user's aspect, which is
        # fed to `home-manager.users.<username>` as with usual integrated home manager configs
        classes = [ "homeManager" ];
      };
    };
  };

  # enable standalone home manager for users on this host (standalone and integrated
  # home manager entities both share the same user aspect `den.aspects.<username>`)
  den.homes.x86_64-linux = {
    "meow@desktop" = {};
  };

  den.aspects.desktop = {
    # aspects to be included on this host regardless of user
    # (note that as of den v0.3.0, any `homeManager` class modules in these includes are
    # automatically forwarded to all users on this host, while `nixos` class modules are
    # evaluated immediately within the context of this host as usual)
    includes = [
      # system
      den.aspects.dual-boot
      den.aspects.firmware
      den.aspects.nixowos
      den.aspects.noctalia-greeter # (note that greeter can manage different WMs/DEs per user)
      den.aspects.nvidia

      # tools
      den.aspects.bottom
      den.aspects.nvtop     # `top` for GPUs
      den.aspects.playerctl # control media players that use MPRIS
      den.aspects.solaar    # logitech mouse config
      den.aspects.tokei

      # other
      den.aspects.firefox
    ];
  };
}
