{
  den.hosts.x86_64-linux.desktop = {
    hostName = "snow-rainbow";
    # this should be kept as the nixos release version of the first install of this system!
    stateVersion = "26.05";

    # declare users on this host
    # host-specific customization for users goes here, host-agnostic customization
    # goes in their autogenerated user aspect (`den.aspects.<username>`)
    users = {
      meow = {
        # enable integrated home manager: allows a `homeManager= {};` class module in user's aspect
        classes = [ "homeManager" ];
      };
    };
  };

  # enable standalone home manager for users on this host (standalone and integrated
  # home manager entities both share the same user aspect `den.aspects.<username>`)
  den.homes.x86_64-linux = {
    "meow@desktop" = {};
  };

  den.aspects.desktop = {
    # aspects to be included on this host regardless of user (so less opinionated)
    includes = [
      # system
      den.aspects.dual-boot
      den.aspects.firmware
      den.aspects.nixowos
      den.aspects.noctalia-greeter # (note that greeter can manage different WMs/DEs per user)
      den.aspects.nvidia

      # tools
      den.aspects.bottom
      den.aspects.nvtop            # `top` for GPUs
      den.aspects.playerctl        # control media players that use MPRIS
      den.aspects.solaar           # logitech mouse config
      den.aspects.tokei

      # other
      den.aspects.firefox
    ];
  };
}
