[location]
auto_locate = false
custom_schedule = true
sunrise = "09:00"
sunset = "18:00"

[theme]
custom_palette = "meow"
mode = "auto"
source = "custom"

[theme.templates]
enable_builtin_templates = true

[shell]
show_location = false
polkit_agent = true
