# keybinds in noctalia panels (e.g. launcher, clipboard)
[keybinds]
validate     = ["return", "kp_enter"]
cancel       = ["escape"]
left         = ["ctrl+shift+h", "left"]
down         = ["ctrl+shift+j", "down"]
up           = ["ctrl+shift+k", "up"]
right        = ["ctrl+shift+l", "right"]
tab_next     = ["tab"]
tab_previous = ["shift+tab", "iso_left_tab"]
copy         = ["ctrl+c"]
save         = ["ctrl+s"]
delete       = ["del"]
