{ den, ... }: {
  # declare custom options/set default options for all host entities, as metadata used for aspects
  den.schema.host = { host, lib, ... }:
    let
      settingsType = import ../_settings_generator.nix {
        inherit den lib;
        aspectTreeRoot = den.aspects;
      };
    in
    {
      options = {
        # required `stateVersion` option in each host entity
        stateVersion = lib.mkOption {
          type = lib.types.str;
        };

        # other optional per-aspect settings that included aspects can declare,
        # which helps modularize our options. generated by _settings_generator.nix
        settings = lib.mkOption {
          type = settingsType;
          default = {};
        };

        # optional `displayOutputs` option in each host entity for wm/de
        #displayOutputs = lib.mkOption {
        #  type = lib.types.listOf (lib.types.submodule {
        #    options = {
        #      name          = lib.mkOption { type = lib.types.str; };
        #      resolution    = lib.mkOption {
        #        type = lib.types.submodule {
        #          options.x = lib.mkOption { type = lib.types.float; };
        #          options.y = lib.mkOption { type = lib.types.float; };
        #        };
        #      };
        #      refreshRate   = lib.mkOption { type = lib.types.float; };
        #      scale         = lib.mkOption { type = lib.types.float; };
        #      position      = lib.mkOption {
        #        type = lib.types.submodule {
        #          options.x = lib.mkOption { type = lib.types.float; };
        #          options.y = lib.mkOption { type = lib.types.float; };
        #        };
        #      };
        #    };
        #  });
        #};
      };

      config = {
        # change default aspect name associated with host entities to fit our naming scheme
        aspect = den.aspects.hosts.${host.name};
      };
    };
}
