[Metadata]
Name=noctalia theme :3
Version=1.0
Author=AnonymousRand

ScaleWithDPI=True

[InputPanel]
# unselected candidate foreground color
NormalColor={{colors.variant_fg_source.default.hex}}

# selected candidate foreground color
HighlightCandidateColor={{colors.selection_fg_source.default.hex}}

[InputPanel/Background]
# input panel background color
# yes i have no idea why it's here, none of this config makes any sense to me
#Color={{colors.variant_bg_source.default.hex}}

# input panel background image (rounded corner in this case)
Image=input_panel_bg.svg

[InputPanel/Highlight]
# selected candidate background color
#Color={{colors.selection_bg_source.default.hex}}

# selected candidate background image (rounded corner in this case)
Image=highlight_bg.svg

# margin settings borrowed from catpuccin fcitx5 theme :3

[InputPanel/TextMargin]
Left=18
Right=18
Top=8
Bottom=8

[InputPanel/Background/Margin]
Left=10
Right=10
Top=10
Bottom=10

[InputPanel/Highlight/Margin]
Left=18
Right=18
Top=8
Bottom=8
